// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  action: dynamic(() => import("./Action")),
  bento: dynamic(() => import("./Bento")),
  construction: dynamic(() => import("./Construction")),
  get_started: dynamic(() => import("./GetStarted")),
  hero: dynamic(() => import("./Hero")),
  hero_2: dynamic(() => import("./ContactUs")),
  integration: dynamic(() => import("./Integration")),
  portfolio: dynamic(() => import("./Portfolio")),
  pricing: dynamic(() => import("./Pricing")),
  rich_text: dynamic(() => import("./RichText")),
  service_options: dynamic(() => import("./ServiceOptions")),
  services: dynamic(() => import("./Services")),
  showcase: dynamic(() => import("./Showcase")),
  team: dynamic(() => import("./Team")),
  values: dynamic(() => import("./Values")),
};
